### ISSUE TITLE
Can't import attached file; floating point error

### ISSUE THREAD

**Issue by westner** [landgraf-dev/openapi-delphi-generator#4]
Hello,

I try to import the attached json-file with:
 
OpenApiDelphiGen.exe -i:"t:\AB-API.json" -o:"T:\" -n:HSAuftrag
 
I get the following error:
 
EConvertError: '#/components/requestBodies/UserWithPassword' is not a valid floating point value
[AB-API.zip](https://github.com/landgraf-dev/openapi-delphi-generator/files/10844876/AB-API.zip)

What is the problem here?

Thanks

Stefan

**Comment by westner** [comment]
Hello,
would it be possible to give this issue a look to identify if I made some error while importing or if it's a bug?

**Comment by wlandgraf** [comment]
We actually have reviewed this and the parser doesn't raise that error anymore (it was caused by a reference in a RequestBody definition).

However, your document has a few schemas with the `allOf` keyword, and that is unfortunately not currently supported by our generator. Thus, I'd say that, for now, you can't use it. Maybe we can implement it in the future.

**Comment by westner** [comment]
Hello,
I downloaded the binary but still get the Floating Point error.

Assuming that I don't need the schemas which use the allOf:
Is the PAS generated at all and only not contains the allOf or fails the generation even if the floating point error is fixed?

**Comment by wlandgraf** [comment]
Sorry, we uploaded the updated binaries now. If the document has ay `allOf`, an import error will be raised. You should remove such constructions from the document.
